T7668: Fix image update due to None kernel options
If we do not have the system options kernel the update fails
Change order for variables `k_cpu_opts` and `k_memory_opts`

If we do not have kernel_options set empty dictionary as
NoneType object has no attribue `get`

```
>>> kernel_options=None
>>> kernel_options.get('cpu', {})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'get'
>>>
>>>
>>> kernel_options={}
>>> kernel_options.get('cpu', {})
{}
>>>
```

(cherry picked from commit 9724b301a0d44854ef7f334de5aedf727713bc52)