ipsec: T7225: "generate ipsec profile ios-remote-access" throws UndefinedError
Calling "generate ipsec profile ios-remote-access rw remote ipsec.vyos.net name
VYOS-NET profile VYOS" in op-mode causes

File "/usr/share/vyos/templates/ipsec/ios_profile.j2", line 58, in top-level template code
  {% if authentication.client_mode.startswith("eap") %}
  ^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'client_mode'

(cherry picked from commit c3a7fdc5cc75949361915db73fbac107ee53edd9)