op-mode: T7403: add option for forcefully remove a container image
If you have multiple images (tags) loaded for a container which point to the
exact same hash - you can only forcefully delete them.

  vyos@vyos:~$ delete container image 70dc5806
  Error: unable to delete image "70dc5806" by ID with more than one tag
    ([registry.io/foo/bar:v1.0 registry.io/foo/bar:v1.0.1]):
    please force removal

In additon an image that is still beeing used can not be removed from the
system as this would cause infinite container restarts.

  vyos@vyos:~$ delete container image all force
  Cannot delete image "d205499ae8bb" because it is currently being used by
  container "3b290f90e83d"!

(cherry picked from commit a99ca6d11b52738f2ce6b49f7417a45cf0f4496f)