ifconfig: fix AttributeError caused by internal race condition
  File "/usr/lib/python3/dist-packages/vyos/ifconfig/interface.py", line 342
    if not self.iftype:
           ^^^^^^^^^^^
AttributeError: 'Interface' object has no attribute 'iftype'

(cherry picked from commit d2a7584a6d5cc3fcd01471b9cfd45735b5458724)