op-mode: T7751: fix re-generating SSH server key causes PermissionError
Fixes an issue when re-generating SSH server key

vyos@vyos:~$ generate ssh server-key
Do you really want to remove the existing SSH host keys? [y/N] y
Traceback (most recent call last):
  File "/usr/libexec/vyos/op_mode/generate_ssh_server_key.py", line 31, in <module>
    cmd('systemctl restart ssh.service')
  File "/usr/lib/python3/dist-packages/vyos/utils/process.py", line 155, in cmd
    raise OSError(code, feedback)
PermissionError: [Errno 1] failed to run command: systemctl restart ssh.service
returned:
exit code: 1

(cherry picked from commit d87266d2726775d76c789e56de3dc24035e15484)